{"name": "Проверка https://dev-api.getprime.pro/api/v1/auth", "status": "failed", "statusDetails": {"message": "AssertionError: assert <Response [404]>\n +  where <Response [404]> = <function post at 0x0000025EBE0F81F0>(url='https://dev-api.getprime.pro/api/v1/auth', headers={'X-API-Key': 'aafe819e-e63c-410d-80eb-29270f45b061', 'X-Merchant-Domain': 'wrongdomain.ru'})\n +    where <function post at 0x0000025EBE0F81F0> = requests.post", "trace": "self = <test_api.TestApiGet object at 0x0000025EBE0EDEE0>\n\n    @pytest.mark.apitest\n    @allure.title(\"Проверка https://dev-api.getprime.pro/api/v1/auth\")\n    @allure.description(\"Невалидная проверка с передачей ключа fronted и с неправильным доменом\")\n    def test_auth_frontend_with_wrong_domain(self):\n        url = \"https://dev-api.getprime.pro/api/v1/auth\"\n        with allure.step(f\"Проверка {url} на код 404\"):\n>           assert requests.post(url=url, headers={'X-API-Key': 'aafe819e-e63c-410d-80eb-29270f45b061','X-Merchant-Domain': 'wrongdomain.ru'})\nE           AssertionError: assert <Response [404]>\nE            +  where <Response [404]> = <function post at 0x0000025EBE0F81F0>(url='https://dev-api.getprime.pro/api/v1/auth', headers={'X-API-Key': 'aafe819e-e63c-410d-80eb-29270f45b061', 'X-Merchant-Domain': 'wrongdomain.ru'})\nE            +    where <function post at 0x0000025EBE0F81F0> = requests.post\n\ntest_api.py:73: AssertionError"}, "description": "Невалидная проверка с передачей ключа fronted и с неправильным доменом", "steps": [{"name": "Проверка https://dev-api.getprime.pro/api/v1/auth на код 404", "status": "failed", "statusDetails": {"message": "AssertionError: assert <Response [404]>\n +  where <Response [404]> = <function post at 0x0000025EBE0F81F0>(url='https://dev-api.getprime.pro/api/v1/auth', headers={'X-API-Key': 'aafe819e-e63c-410d-80eb-29270f45b061', 'X-Merchant-Domain': 'wrongdomain.ru'})\n +    where <function post at 0x0000025EBE0F81F0> = requests.post\n", "trace": "  File \"C:\\Users\\Qasquad1\\PycharmProjects\\GetPrime\\tests\\test_api.py\", line 73, in test_auth_frontend_with_wrong_domain\n    assert requests.post(url=url, headers={'X-API-Key': 'aafe819e-e63c-410d-80eb-29270f45b061','X-Merchant-Domain': 'wrongdomain.ru'})\n"}, "start": 1751968500746, "stop": 1751968501015}], "start": 1751968500746, "stop": 1751968501015, "uuid": "a5e8c0c1-141a-41e1-944c-1147adce051d", "historyId": "ea0ea4d956e4ada3343a212a328a61a8", "testCaseId": "ea0ea4d956e4ada3343a212a328a61a8", "fullName": "tests.test_api.TestApiGet#test_auth_frontend_with_wrong_domain", "labels": [{"name": "tag", "value": "apitest"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestApiGet"}, {"name": "host", "value": "Robotek3000"}, {"name": "thread", "value": "7604-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api"}]}