{"name": "Проверка Проверка https://dev-api.getprime.pro/api/v1/certificates/catalog - Invalid Token", "status": "failed", "statusDetails": {"message": "AssertionError: Текст не соответствует\nassert 'У вас нет прав для выполнения этого действия.' == 'У ваcс нет прав для выполнения этого действия.'\n  \n  - У ваcс нет прав для выполнения этого действия.\n  ?     -\n  + У вас нет прав для выполнения этого действия.", "trace": "self = <test_api.TestApiGet object at 0x000002B5FD7A36D0>\n\n    @pytest.mark.apitest\n    @allure.title(\"Проверка Проверка https://dev-api.getprime.pro/api/v1/certificates/catalog - Invalid Token\")\n    @allure.description(\"Негативна проверка catalog с невалидным ключом авторизации в хедере\")\n    def test_certificate_catalog_invalid_token(self):\n        url_certificates_catalog = os.getenv(\"url_certificates_catalog\")\n        with allure.step(f\"Проверка {url_certificates_catalog} на 403\"):\n            response = requests.get(url=url_certificates_catalog, headers={\"Authorization\": \"invalid_token\"})\n            assert response.status_code == 403, \"Статус код не 403\"\n            json_response = response.json()\n        with allure.step(\n                f\"Проверка текста message. Ожидали текст 'У вас нет прав для выполнения этого действия.', Получили текст '{json_response['message']}'\"):\n>           assert json_response['message'] == \"У ваcс нет прав для выполнения этого действия.\", \"Текст не соответствует\"\nE           AssertionError: Текст не соответствует\nE           assert 'У вас нет прав для выполнения этого действия.' == 'У ваcс нет прав для выполнения этого действия.'\nE             \nE             - У ваcс нет прав для выполнения этого действия.\nE             ?     -\nE             + У вас нет прав для выполнения этого действия.\n\ntest_api.py:262: AssertionError"}, "description": "Негативна проверка catalog с невалидным ключом авторизации в хедере", "steps": [{"name": "Проверка https://dev-api.getprime.pro/api/v1/certificates/catalog на 403", "status": "passed", "start": 1753250674639, "stop": 1753250674994}, {"name": "Проверка текста message. Ожидали текст 'У вас нет прав для выполнения этого действия.', Получили текст 'У вас нет прав для выполнения этого действия.'", "status": "failed", "statusDetails": {"message": "AssertionError: Текст не соответствует\nassert 'У вас нет прав для выполнения этого действия.' == 'У ваcс нет прав для выполнения этого действия.'\n  \n  - У ваcс нет прав для выполнения этого действия.\n  ?     -\n  + У вас нет прав для выполнения этого действия.\n", "trace": "  File \"C:\\Users\\Qasquad1\\PycharmProjects\\GetPrime\\tests\\test_api.py\", line 262, in test_certificate_catalog_invalid_token\n    assert json_response['message'] == \"У ваcс нет прав для выполнения этого действия.\", \"Текст не соответствует\"\n"}, "start": 1753250674994, "stop": 1753250674995}], "start": 1753250674638, "stop": 1753250674996, "uuid": "b6ffef35-10be-4553-a52a-62785468f1af", "historyId": "9514066872f57b73b23ceb441d0778f8", "testCaseId": "9514066872f57b73b23ceb441d0778f8", "fullName": "tests.test_api.TestApiGet#test_certificate_catalog_invalid_token", "labels": [{"name": "tag", "value": "apitest"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestApiGet"}, {"name": "host", "value": "Robotek3000"}, {"name": "thread", "value": "5956-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api"}]}