{"name": "Проверка Проверка https://dev-api.getprime.pro/api/v1/certificates/catalog -  No Token", "status": "failed", "statusDetails": {"message": "AssertionError: Текст не соответствует\nassert 'У вас нет прав для выполнения этого действия.' == 'У вас нет праваа для выполнения этого действия.'\n  \n  - У вас нет праваа для выполнения этого действия.\n  ?               --\n  + У вас нет прав для выполнения этого действия.", "trace": "self = <test_api.TestApiGet object at 0x00000193EED32E20>\n\n    @pytest.mark.apitest\n    @allure.title(\"Проверка Проверка https://dev-api.getprime.pro/api/v1/certificates/catalog -  No Token\")\n    @allure.description(\n        \"Негативна проверка catalog без ключа авторизации в хедере\" )\n    def test_certificate_catalog_no_token(self):\n        url_certificates_catalog = os.getenv(\"url_certificates_catalog\")\n        with allure.step(f\"Проверка {url_certificates_catalog} на 403 \"):\n            response = requests.get(url=url_certificates_catalog)\n            assert response.status_code == 403, \"статус код не 403\"\n            json_response = response.json()\n>           assert json_response['message'] == \"У вас нет праваа для выполнения этого действия.\", \"Текст не соответствует\"\nE           AssertionError: Текст не соответствует\nE           assert 'У вас нет прав для выполнения этого действия.' == 'У вас нет праваа для выполнения этого действия.'\nE             \nE             - У вас нет праваа для выполнения этого действия.\nE             ?               --\nE             + У вас нет прав для выполнения этого действия.\n\ntest_api.py:238: AssertionError"}, "description": "Негативна проверка catalog без ключа авторизации в хедере", "steps": [{"name": "Проверка https://dev-api.getprime.pro/api/v1/certificates/catalog на 403 ", "status": "failed", "statusDetails": {"message": "AssertionError: Текст не соответствует\nassert 'У вас нет прав для выполнения этого действия.' == 'У вас нет праваа для выполнения этого действия.'\n  \n  - У вас нет праваа для выполнения этого действия.\n  ?               --\n  + У вас нет прав для выполнения этого действия.\n", "trace": "  File \"C:\\Users\\Qasquad1\\PycharmProjects\\GetPrime\\tests\\test_api.py\", line 238, in test_certificate_catalog_no_token\n    assert json_response['message'] == \"У вас нет праваа для выполнения этого действия.\", \"Текст не соответствует\"\n"}, "start": 1753241828926, "stop": 1753241829266}], "start": 1753241828925, "stop": 1753241829267, "uuid": "12b8e05d-3bf0-4c58-a0da-c35548618eba", "historyId": "326821f1b12d6636b9f41c750f82fe41", "testCaseId": "326821f1b12d6636b9f41c750f82fe41", "fullName": "tests.test_api.TestApiGet#test_certificate_catalog_no_token", "labels": [{"name": "tag", "value": "apitest"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestApiGet"}, {"name": "host", "value": "Robotek3000"}, {"name": "thread", "value": "8928-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api"}]}